### ISSUE TITLE
Unexpected write permission required for `general/last.pt`?

### ISSUE THREAD

**Issue by BioinfoTongLI** [weigertlab/spotiflow#23]
**Describe the bug**
spotiflow asks for writing permissions in the folder of pretrained models.
This is raising an issue when the pretrained models is downloaded into a container, where it's ready-only

**exepcted behaviour**
Spotiflow should just load the models from the directory and not try to write anything there(?)

**To Reproduce**
run a standard prediction with `general` model

**Environment (please complete the following information):**
 - Spotiflow version: 0.5.1
 - OS: linux
 - OS version: 22.04

**Additional context**

**Comment by AlbertDominguez** [comment]
Hi @BioinfoTongLI,

I tried to replicate by using a read-only cache directory and having the model placed there beforehand but it seems to load normally. Could you paste here the relevant Dockerfile lines (e.g. copying the model to the dir)? Is the model unzipped by the dockerfile or it just transfers the zip?

**Comment by BioinfoTongLI** [comment]
Hi @AlbertDominguez, sure! many thanks for your reply!
Here it is.
https://github.com/BioinfoTongLI/containers/blob/main/spotiflow/0.5.1-py11/Dockerfile
I've checked that indeed it loaded successfully with Docker. But not with singularity.

Here's the actually error mesage.
```
Python 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:27:36) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from spotiflow.model import Spotiflow
>>> from spotiflow.model import Spotiflow
>>> Spotiflow.from_pretrained('general')
INFO:spotiflow.model.spotiflow:Loading pretrained model: general
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/site-packages/spotiflow/model/spotiflow.py", line 229, in from_pretrained
    pretrained_path = get_pretrained_model_path(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/spotiflow/model/pretrained.py", line 46, in get_pretrained_model_path
    get_file(
  File "/opt/conda/lib/python3.11/site-packages/spotiflow/utils/get_file.py", line 597, in get_file
    _extract_archive(fpath, datadir, archive_format)
  File "/opt/conda/lib/python3.11/site-packages/spotiflow/utils/get_file.py", line 158, in _extract_archive
    archive.extractall(path)
  File "/opt/conda/lib/python3.11/zipfile.py", line 1702, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/opt/conda/lib/python3.11/zipfile.py", line 1756, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/models/general/last.pt'
```
I will try to find out if it's a singularity-specific issue.

**Comment by AlbertDominguez** [comment]
Hi @BioinfoTongLI, I just released 0.5.2 which should have fixed the bug. I'm closing the issue, but feel free to reopen if it does not work as expected! Thanks for reporting :)
